version: '3'

services:
    finances-front:     
        image: thiagoalvesfoz/finances-front:latest
        depends_on:
            - finances-api
        tty: true
        networks:
            - my-finances
        ports:
            - "80:80"
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
            restart_policy:
                condition: on-failure


    finances-api:        
        image: thiagoalvesfoz/api-finances:latest
        depends_on:
            - finances-db
        networks:
            - my-finances
        ports:
            - "8080:8080"
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
            restart_policy:
                condition: on-failure

    finances-db:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: financas
            POSTGRES_PASSWORD: 1234567
        volumes:
            - ./dump/:/docker-entrypoint-initdb.d
        networks:
            - my-finances
        deploy:
            placement:
                constraints: [node.role == manager]

networks:
    my-finances:
